name: "Get GitHub Packages"
description: "Discovers and filters packages from a GitHub organization by type and repository"
inputs:
  source-org:
    description: "The source organization from which to get packages"
    required: true
  source-api-url:
    description: "The source GitHub API URL (e.g., https://api.github.com)"
    required: true
    default: "https://api.github.com"
  gh-source-pat:
    description: "GitHub PAT for reading packages from source host (needs read:packages scope)"
    required: true
  repo-name:
    description: "Repository name to filter packages by. If not provided, will get packages without a linked repository"
    required: false
  package-types:
    description: "The package types to gather information about, comma separated. Options are: npm, maven, rubygems, docker, nuget, container"
    required: false
    default: "npm, nuget, container"
outputs:
  npm-packages:
    description: "JSON array of npm packages found matching criteria"
  npm-count:
    description: "Number of npm packages found"
  container-packages:
    description: "JSON array of Container packages found matching criteria"
  container-count:
    description: "Number of Container packages found"
  nuget-packages:
    description: "JSON array of NuGet packages found matching criteria"
  nuget-count:
    description: "Number of NuGet packages found"
  rubygems-packages:
    description: "JSON array of RubyGem packages found matching criteria"
  rubygems-count:
    description: "Number of RubyGem packages found"
  maven-packages:
    description: "JSON array of Maven packages found matching criteria"
  maven-count:
    description: "Number of Maven packages found"
  all-packages:
    description: "JSON object containing all packages by type"
  total-count:
    description: "Total number of packages found across all types"
runs:
  using: "node20"
  main: "dist/index.js"
