name: "Migrate NuGet Packages"
description: "GitHub Action to migrate NuGet packages between GitHub organizations"
inputs:
  source-org:
    description: "The source organization from which to migrate NuGet packages"
    required: true
  source-api-url:
    description: "The source GitHub API URL (e.g., https://api.github.com)"
    required: true
    default: "https://api.github.com"
  source-registry-url:
    description: "The source NuGet registry URL. If not provided, will be derived from the API URL."
    required: false
  target-org:
    description: "The target organization to which to migrate NuGet packages"
    required: true
  target-api-url:
    description: "The target GitHub API URL (e.g., https://api.github.com)"
    required: true
    default: "https://api.github.com"
  target-registry-url:
    description: "The target NuGet registry URL. If not provided, will be derived from the API URL."
    required: false
  gh-source-pat:
    description: "GitHub PAT for reading packages from source host"
    required: true
  gh-target-pat:
    description: "GitHub PAT for writing packages to target host"
    required: true
  packages:
    description: "JSON array of NuGet packages to migrate (from get-packages-action output)"
    required: true
outputs:
  result:
    description: "The results of the migration process as a JSON array with success/failure counts for each package"
runs:
  using: "node20"
  main: "dist/index.js"
