on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Repository name to filter packages (leave empty for packages without repo)"
        required: false
run-name: Migrating ${{ inputs.repo_name || 'Org'}} packages
name: Migrate GitHub Packages

jobs:
  get-packages:
    runs-on: ubuntu-latest
    outputs:
      npm_packages: ${{ steps.get-packages.outputs.npm_packages }}
      npm_count: ${{ steps.get-packages.outputs.npm_count }}
      container_packages: ${{ steps.get-packages.outputs.container_packages }}
      container_count: ${{ steps.get-packages.outputs.container_count }}
      nuget_packages: ${{ steps.get-packages.outputs.nuget_packages }}
      nuget_count: ${{ steps.get-packages.outputs.nuget_count }}
      rubygems_packages: ${{ steps.get-packages.outputs.rubygems_packages }}
      rubygems_count: ${{ steps.get-packages.outputs.rubygems_count }}
      maven_packages: ${{ steps.get-packages.outputs.maven_packages }}
      maven_count: ${{ steps.get-packages.outputs.maven_count }}
      all_packages: ${{ steps.get-packages.outputs.all_packages }}
      total_count: ${{ steps.get-packages.outputs.total_count }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get packages
        id: get-packages
        uses: ./get-packages-action
        with:
          source_org: ${{ vars.source_org }}
          source_api_url: ${{ vars.source_api_url }}
          gh_source_pat: ${{ secrets.GH_SOURCE_PAT }}
          repo_name: ${{ github.event.inputs.repo_name }}

  list-outputs:
    runs-on: ubuntu-latest
    needs: get-packages
    steps:
      - name: Write step summary
        if: always()
        id: write-output
        run: |
          echo "NPM packages found: ${{ needs.get-packages.outputs.npm_count }}"
          echo "Container packages found: ${{ needs.get-packages.outputs.container_count }}"
          echo "NuGet packages found: ${{ needs.get-packages.outputs.nuget_count }}"
          echo "RubyGems packages found: ${{ needs.get-packages.outputs.rubygems_count }}"
          echo "Maven packages found: ${{ needs.get-packages.outputs.maven_count }}"
          echo "Total packages found: ${{ needs.get-packages.outputs.total_count }}"
          echo "------"
          echo "All packages found: ${{ needs.get-packages.outputs.all_packages }}"
          echo "NPM packages: ${{ needs.get-packages.outputs.npm_packages }}"
          echo "Container packages: ${{ needs.get-packages.outputs.container_packages }}"
          echo "NuGet packages: ${{ needs.get-packages.outputs.nuget_packages }}"
          echo "RubyGems packages: ${{ needs.get-packages.outputs.rubygems_packages }}"
          echo "Maven packages: ${{ needs.get-packages.outputs.maven_packages }}"
          echo "------"
          echo "output: ${{ needs.get-packages.outputs }}"
          echo "output: ${{ toJson(needs.get-packages.outputs) }}"

  migrate-nuget:
    runs-on: ubuntu-latest
    needs: get-packages
    if: needs.get-packages.outputs.nuget_count > 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Migrate NuGet packages
        uses: ./migrate-nuget-packages-action
        id: migrate-nuget
        with:
          source_org: ${{ vars.source_org }}
          source_api_url: ${{ vars.source_api_url }}
          target_org: ${{ vars.target_org }}
          target_api_url: ${{ vars.target_api_url }}
          gh_source_pat: ${{ secrets.GH_SOURCE_PAT }}
          gh_target_pat: ${{ secrets.GH_TARGET_PAT }}
          packages: ${{ needs.get-packages.outputs.nuget_packages }}

  migrate-npm:
    runs-on: ubuntu-latest
    needs: get-packages
    if: needs.get-packages.outputs.npm_count > 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Migrate npm packages
        uses: ./migrate-npm-packages-action
        id: migrate-npm
        with:
          source_org: ${{ vars.source_org }}
          source_api_url: ${{ vars.source_api_url }}
          target_org: ${{ vars.target_org }}
          target_api_url: ${{ vars.target_api_url }}
          gh_source_pat: ${{ secrets.GH_SOURCE_PAT }}
          gh_target_pat: ${{ secrets.GH_TARGET_PAT }}
          packages: ${{ needs.get-packages.outputs.npm_packages }}
          repo_name: ${{ github.event.inputs.repo_name }}

  migrate-container:
    runs-on: ubuntu-latest
    needs: get-packages
    if: needs.get-packages.outputs.container_count > 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Migrate Container packages
        uses: ./migrate-container-packages-action
        id: migrate-container
        with:
          source_org: ${{ vars.source_org }}
          source_api_url: ${{ vars.source_api_url }}
          target_org: ${{ vars.target_org }}
          target_api_url: ${{ vars.target_api_url }}
          gh_source_pat: ${{ secrets.GH_SOURCE_PAT }}
          gh_target_pat: ${{ secrets.GH_TARGET_PAT }}
          packages: ${{ needs.get-packages.outputs.container_packages }}
