on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: "Repository name to filter packages (leave empty for packages without repo)"
        required: false

jobs:
  get-packages:
    runs-on: ubuntu-latest
    outputs:
      npm-packages: ${{ steps.get-packages.outputs.npm-packages }}
      npm-count: ${{ steps.get-packages.outputs.npm-count }}
      container-packages: ${{ steps.get-packages.outputs.container-packages }}
      container-count: ${{ steps.get-packages.outputs.container-count }}
      nuget-packages: ${{ steps.get-packages.outputs.nuget-packages }}
      nuget-count: ${{ steps.get-packages.outputs.nuget-count }}
      rubygems-packages: ${{ steps.get-packages.outputs.rubygems-packages }}
      rubygems-count: ${{ steps.get-packages.outputs.rubygems-count }}
      maven-packages: ${{ steps.get-packages.outputs.maven-packages }}
      maven-count: ${{ steps.get-packages.outputs.maven-count }}
      all-packages: ${{ steps.get-packages.outputs.all-packages }}
      total-count: ${{ steps.get-packages.outputs.total-count }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get packages
        id: get-packages
        uses: ./get-packages-action
        with:
          source-org: ${{ vars.source_org }}
          source-api-url: ${{ vars.source_api_url }}
          gh-source-pat: ${{ secrets.GH_SOURCE_PAT }}
          repo-name: ${{ github.event.inputs.repo-name }}

  list-outputs:
    runs-on: ubuntu-latest
    needs: get-packages
    steps:
      - name: Write step summary
        if: always()
        id: write-output
        run: |
          echo "NPM packages found: ${{ needs.get-packages.outputs.npm-count }}"
          echo "Container packages found: ${{ needs.get-packages.outputs.container-count }}"
          echo "NuGet packages found: ${{ needs.get-packages.outputs.nuget-count }}"
          echo "RubyGems packages found: ${{ needs.get-packages.outputs.rubygems-count }}"
          echo "Maven packages found: ${{ needs.get-packages.outputs.maven-count }}"
          echo "Total packages found: ${{ needs.get-packages.outputs.total-count }}"
          echo "------"
          echo "All packages found: ${{ needs.get-packages.outputs.all-packages }}"
          echo "NPM packages: ${{ needs.get-packages.outputs.npm-packages }}"
          echo "Container packages: ${{ needs.get-packages.outputs.container-packages }}"
          echo "NuGet packages: ${{ needs.get-packages.outputs.nuget-packages }}"
          echo "RubyGems packages: ${{ needs.get-packages.outputs.rubygems-packages }}"
          echo "Maven packages: ${{ needs.get-packages.outputs.maven-packages }}"
          echo "------"
          echo "output: ${{ needs.get-packages.outputs }}"
          echo "output: ${{ toJson(needs.get-packages.outputs) }}"

  migrate-nuget:
    runs-on: ubuntu-latest
    needs: get-packages
    if: needs.get-packages.outputs.nuget-count > 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Migrate NuGet packages
        uses: ./migrate-nuget-packages-action
        id: migrate-nuget
        with:
          source-org: ${{ vars.source_org }}
          source-api-url: ${{ vars.source_api_url }}
          target-org: ${{ vars.target_org }}
          target-api-url: ${{ vars.target_api_url }}
          gh-source-pat: ${{ secrets.GH_SOURCE_PAT }}
          gh-target-pat: ${{ secrets.GH_TARGET_PAT }}
          packages: ${{ needs.get-packages.outputs.nuget-packages }}

      - name: Write step summary
        if: always()
        id: write-output
        run: |
          echo ${{ steps.migrate-nuget.outputs.result }} > $GITHUB_STEP_SUMMARY
          # echo "NuGet packages migrated: ${{ steps.migrate-nuget.outputs.result }}"
          # echo "NuGet packages failed: ${{ steps.migrate-nuget.outputs.failed }}"
          # echo "NuGet packages succeeded: ${{ steps.migrate-nuget.outputs.succeeded }}"
          # echo "NuGet packages skipped: ${{ steps.migrate-nuget.outputs.skipped }}"

  migrate-npm:
    runs-on: ubuntu-latest
    needs: get-packages
    if: needs.get-packages.outputs.npm-count > 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Migrate npm packages
        uses: ./migrate-npm-packages-action
        id: migrate-npm
        with:
          source-org: ${{ vars.source_org }}
          source-api-url: ${{ vars.source_api_url }}
          target-org: ${{ vars.target_org }}
          target-api-url: ${{ vars.target_api_url }}
          gh-source-pat: ${{ secrets.GH_SOURCE_PAT }}
          gh-target-pat: ${{ secrets.GH_TARGET_PAT }}
          packages: ${{ needs.get-packages.outputs.npm-packages }}
      - name: Write step summary
        if: always()
        id: write-output
        run: |
          echo ${{ steps.migrate-npm.outputs.result }} > $GITHUB_STEP_SUMMARY

  migrate-container:
    runs-on: ubuntu-latest
    needs: get-packages
    if: needs.get-packages.outputs.container-count > 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Migrate Container packages
        uses: ./migrate-container-packages-action
        id: migrate-container
        with:
          source-org: ${{ vars.source_org }}
          source-api-url: ${{ vars.source_api_url }}
          target-org: ${{ vars.target_org }}
          target-api-url: ${{ vars.target_api_url }}
          gh-source-pat: ${{ secrets.GH_SOURCE_PAT }}
          gh-target-pat: ${{ secrets.GH_TARGET_PAT }}
          packages: ${{ needs.get-packages.outputs.container-packages }}

      - name: Write step summary
        if: always()
        id: write-output
        run: |
          echo ${{ steps.migrate-container.outputs.result }} > $GITHUB_STEP_SUMMARY
          # echo "Container packages migrated: ${{ steps.migrate-container.outputs.result }}"
          # echo "Container packages failed: ${{ steps.migrate-container.outputs.failed }}"
          # echo "Container packages succeeded: ${{ steps.migrate-container.outputs.succeeded }}"
          # echo "Container packages skipped: ${{ steps.migrate-container.outputs.skipped }}"
